// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSpHQ40NvrsT7l2X9FsmdZki4a-tS7Bl8',
    appId: '1:570279047715:web:90c3daf04f130272fbf796',
    messagingSenderId: '570279047715',
    projectId: 'alpharapp-ec491',
    authDomain: 'alpharapp-ec491.firebaseapp.com',
    storageBucket: 'alpharapp-ec491.firebasestorage.app',
    measurementId: 'G-M8F56ZG7NX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGDvM5LogQlAizoO8vuKNV7hyaIPhhUFM',
    appId: '1:570279047715:android:1cc54c68bc1460fdfbf796',
    messagingSenderId: '570279047715',
    projectId: 'alpharapp-ec491',
    storageBucket: 'alpharapp-ec491.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDa8DqQfejJRZ5AwPc09dpL1Ldace_9hZI',
    appId: '1:570279047715:ios:b79e4b1b63335e19fbf796',
    messagingSenderId: '570279047715',
    projectId: 'alpharapp-ec491',
    storageBucket: 'alpharapp-ec491.firebasestorage.app',
    iosBundleId: 'com.theone.phar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDa8DqQfejJRZ5AwPc09dpL1Ldace_9hZI',
    appId: '1:570279047715:ios:de76cc8360775417fbf796',
    messagingSenderId: '570279047715',
    projectId: 'alpharapp-ec491',
    storageBucket: 'alpharapp-ec491.firebasestorage.app',
    iosBundleId: 'com.abolashine.theOne.abolashin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSpHQ40NvrsT7l2X9FsmdZki4a-tS7Bl8',
    appId: '1:570279047715:web:81397b0bc8d29d62fbf796',
    messagingSenderId: '570279047715',
    projectId: 'alpharapp-ec491',
    authDomain: 'alpharapp-ec491.firebaseapp.com',
    storageBucket: 'alpharapp-ec491.firebasestorage.app',
    measurementId: 'G-B330MXVMTB',
  );
}
